/* 
Data adapted from 
https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes

What is a country, and what is a capital, can vary depending on who you ask. 
The World Bank doesn't list a capital city for some of the countries in the list 
linked to above, so those have been removed from the array of data. 
*/

let countriesAndCodes = [
    {'name':'Afghanistan', 'letterCode':'AF', 'countryCode':'004'},
    {'name':'Albania', 'letterCode':'AL', 'countryCode':'008'},
    {'name':'Algeria', 'letterCode':'DZ', 'countryCode':'012'},
    {'name':'American Samoa', 'letterCode':'AS', 'countryCode':'016'},
    {'name':'Andorra', 'letterCode':'AD', 'countryCode':'020'},
    {'name':'Angola', 'letterCode':'AO', 'countryCode':'024'},
    {'name':'Antigua and Barbuda', 'letterCode':'AG', 'countryCode':'028'},
    {'name':'Argentina', 'letterCode':'AR', 'countryCode':'032'},
    {'name':'Armenia', 'letterCode':'AM', 'countryCode':'051'},
    {'name':'Aruba', 'letterCode':'AW', 'countryCode':'533'},
    {'name':'Australia', 'letterCode':'AU', 'countryCode':'036'},
    {'name':'Austria', 'letterCode':'AT', 'countryCode':'040'},
    {'name':'Azerbaijan', 'letterCode':'AZ', 'countryCode':'031'},
    {'name':'Bahamas', 'letterCode':'BS', 'countryCode':'044'},
    {'name':'Bahrain', 'letterCode':'BH', 'countryCode':'048'},
    {'name':'Bangladesh', 'letterCode':'BD', 'countryCode':'050'},
    {'name':'Barbados', 'letterCode':'BB', 'countryCode':'052'},
    {'name':'Belarus', 'letterCode':'BY', 'countryCode':'112'},
    {'name':'Belgium', 'letterCode':'BE', 'countryCode':'056'},
    {'name':'Belize', 'letterCode':'BZ', 'countryCode':'084'},
    {'name':'Benin', 'letterCode':'BJ', 'countryCode':'204'},
    {'name':'Bermuda', 'letterCode':'BM', 'countryCode':'060'},
    {'name':'Bhutan', 'letterCode':'BT', 'countryCode':'064'},
    {'name':'Bolivia (Plurinational State of)', 'letterCode':'BO', 'countryCode':'068'},
    {'name':'Bosnia and Herzegovina', 'letterCode':'BA', 'countryCode':'070'},
    {'name':'Botswana', 'letterCode':'BW', 'countryCode':'072'},
    {'name':'Brazil', 'letterCode':'BR', 'countryCode':'076'},
    {'name':'Brunei Darussalam', 'letterCode':'BN', 'countryCode':'096'},
    {'name':'Bulgaria', 'letterCode':'BG', 'countryCode':'100'},
    {'name':'Burkina Faso', 'letterCode':'BF', 'countryCode':'854'},
    {'name':'Burundi', 'letterCode':'BI', 'countryCode':'108'},
    {'name':'Cabo Verde', 'letterCode':'CV', 'countryCode':'132'},
    {'name':'Cambodia', 'letterCode':'KH', 'countryCode':'116'},
    {'name':'Cameroon', 'letterCode':'CM', 'countryCode':'120'},
    {'name':'Canada', 'letterCode':'CA', 'countryCode':'124'},
    {'name':'Cayman Islands', 'letterCode':'KY', 'countryCode':'136'},
    {'name':'Central African Republic', 'letterCode':'CF', 'countryCode':'140'},
    {'name':'Chad', 'letterCode':'TD', 'countryCode':'148'},
    {'name':'Chile', 'letterCode':'CL', 'countryCode':'152'},
    {'name':'China', 'letterCode':'CN', 'countryCode':'156'},
    {'name':'Colombia', 'letterCode':'CO', 'countryCode':'170'},
    {'name':'Comoros', 'letterCode':'KM', 'countryCode':'174'},
    {'name':'Congo', 'letterCode':'CG', 'countryCode':'178'},
    {'name':'Congo (Democratic Republic of the)', 'letterCode':'CD', 'countryCode':'180'},
    {'name':'Costa Rica', 'letterCode':'CR', 'countryCode':'188'},
    {'name':'Côte d'Ivoire', 'letterCode':'CI', 'countryCode':'384'},
    {'name':'Croatia', 'letterCode':'HR', 'countryCode':'191'},
    {'name':'Cuba', 'letterCode':'CU', 'countryCode':'192'},
    {'name':'Curaçao', 'letterCode':'CW', 'countryCode':'531'},
    {'name':'Cyprus', 'letterCode':'CY', 'countryCode':'196'},
    {'name':'Czechia', 'letterCode':'CZ', 'countryCode':'203'},
    {'name':'Denmark', 'letterCode':'DK', 'countryCode':'208'},
    {'name':'Djibouti', 'letterCode':'DJ', 'countryCode':'262'},
    {'name':'Dominica', 'letterCode':'DM', 'countryCode':'212'},
    {'name':'Dominican Republic', 'letterCode':'DO', 'countryCode':'214'},
    {'name':'Ecuador', 'letterCode':'EC', 'countryCode':'218'},
    {'name':'Egypt', 'letterCode':'EG', 'countryCode':'818'},
    {'name':'El Salvador', 'letterCode':'SV', 'countryCode':'222'},
    {'name':'Equatorial Guinea', 'letterCode':'GQ', 'countryCode':'226'},
    {'name':'Eritrea', 'letterCode':'ER', 'countryCode':'232'},
    {'name':'Estonia', 'letterCode':'EE', 'countryCode':'233'},
    {'name':'Eswatini', 'letterCode':'SZ', 'countryCode':'748'},
    {'name':'Ethiopia', 'letterCode':'ET', 'countryCode':'231'},
    {'name':'Faroe Islands', 'letterCode':'FO', 'countryCode':'234'},
    {'name':'Fiji', 'letterCode':'FJ', 'countryCode':'242'},
    {'name':'Finland', 'letterCode':'FI', 'countryCode':'246'},
    {'name':'France', 'letterCode':'FR', 'countryCode':'250'},
    {'name':'French Polynesia', 'letterCode':'PF', 'countryCode':'258'},
    {'name':'Gabon', 'letterCode':'GA', 'countryCode':'266'},
    {'name':'Gambia', 'letterCode':'GM', 'countryCode':'270'},
    {'name':'Georgia', 'letterCode':'GE', 'countryCode':'268'},
    {'name':'Germany', 'letterCode':'DE', 'countryCode':'276'},
    {'name':'Ghana', 'letterCode':'GH', 'countryCode':'288'},
    {'name':'Greece', 'letterCode':'GR', 'countryCode':'300'},
    {'name':'Greenland', 'letterCode':'GL', 'countryCode':'304'},
    {'name':'Grenada', 'letterCode':'GD', 'countryCode':'308'},
    {'name':'Guam', 'letterCode':'GU', 'countryCode':'316'},
    {'name':'Guatemala', 'letterCode':'GT', 'countryCode':'320'},
    {'name':'Guinea', 'letterCode':'GN', 'countryCode':'324'},
    {'name':'Guinea-Bissau', 'letterCode':'GW', 'countryCode':'624'},
    {'name':'Guyana', 'letterCode':'GY', 'countryCode':'328'},
    {'name':'Haiti', 'letterCode':'HT', 'countryCode':'332'},
    {'name':'Honduras', 'letterCode':'HN', 'countryCode':'340'},
    {'name':'Hungary', 'letterCode':'HU', 'countryCode':'348'},
    {'name':'Iceland', 'letterCode':'IS', 'countryCode':'352'},
    {'name':'India', 'letterCode':'IN', 'countryCode':'356'},
    {'name':'Indonesia', 'letterCode':'ID', 'countryCode':'360'},
    {'name':'Iran (Islamic Republic of)', 'letterCode':'IR', 'countryCode':'364'},
    {'name':'Iraq', 'letterCode':'IQ', 'countryCode':'368'},
    {'name':'Ireland', 'letterCode':'IE', 'countryCode':'372'},
    {'name':'Isle of Man', 'letterCode':'IM', 'countryCode':'833'},
    {'name':'Italy', 'letterCode':'IT', 'countryCode':'380'},
    {'name':'Jamaica', 'letterCode':'JM', 'countryCode':'388'},
    {'name':'Japan', 'letterCode':'JP', 'countryCode':'392'},
    {'name':'Jordan', 'letterCode':'JO', 'countryCode':'400'},
    {'name':'Kazakhstan', 'letterCode':'KZ', 'countryCode':'398'},
    {'name':'Kenya', 'letterCode':'KE', 'countryCode':'404'},
    {'name':'Kiribati', 'letterCode':'KI', 'countryCode':'296'},
    {'name':'Korea (Democratic People's Republic of)', 'letterCode':'KP', 'countryCode':'408'},
    {'name':'Korea (Republic of)', 'letterCode':'KR', 'countryCode':'410'},
    {'name':'Kuwait', 'letterCode':'KW', 'countryCode':'414'},
    {'name':'Kyrgyzstan', 'letterCode':'KG', 'countryCode':'417'},
    {'name':'Lao People's Democratic Republic', 'letterCode':'LA', 'countryCode':'418'},
    {'name':'Latvia', 'letterCode':'LV', 'countryCode':'428'},
    {'name':'Lebanon', 'letterCode':'LB', 'countryCode':'422'},
    {'name':'Lesotho', 'letterCode':'LS', 'countryCode':'426'},
    {'name':'Liberia', 'letterCode':'LR', 'countryCode':'430'},
    {'name':'Libya', 'letterCode':'LY', 'countryCode':'434'},
    {'name':'Liechtenstein', 'letterCode':'LI', 'countryCode':'438'},
    {'name':'Lithuania', 'letterCode':'LT', 'countryCode':'440'},
    {'name':'Luxembourg', 'letterCode':'LU', 'countryCode':'442'},
    {'name':'Macedonia (the former Yugoslav Republic of)', 'letterCode':'MK', 'countryCode':'807'},
    {'name':'Madagascar', 'letterCode':'MG', 'countryCode':'450'},
    {'name':'Malawi', 'letterCode':'MW', 'countryCode':'454'},
    {'name':'Malaysia', 'letterCode':'MY', 'countryCode':'458'},
    {'name':'Maldives', 'letterCode':'MV', 'countryCode':'462'},
    {'name':'Mali', 'letterCode':'ML', 'countryCode':'466'},
    {'name':'Malta', 'letterCode':'MT', 'countryCode':'470'},
    {'name':'Marshall Islands', 'letterCode':'MH', 'countryCode':'584'},
    {'name':'Mauritania', 'letterCode':'MR', 'countryCode':'478'},
    {'name':'Mauritius', 'letterCode':'MU', 'countryCode':'480'},
    {'name':'Mexico', 'letterCode':'MX', 'countryCode':'484'},
    {'name':'Micronesia (Federated States of)', 'letterCode':'FM', 'countryCode':'583'},
    {'name':'Moldova (Republic of)', 'letterCode':'MD', 'countryCode':'498'},
    {'name':'Monaco', 'letterCode':'MC', 'countryCode':'492'},
    {'name':'Mongolia', 'letterCode':'MN', 'countryCode':'496'},
    {'name':'Montenegro', 'letterCode':'ME', 'countryCode':'499'},
    {'name':'Morocco', 'letterCode':'MA', 'countryCode':'504'},
    {'name':'Mozambique', 'letterCode':'MZ', 'countryCode':'508'},
    {'name':'Myanmar', 'letterCode':'MM', 'countryCode':'104'},
    {'name':'Namibia', 'letterCode':'NA', 'countryCode':'516'},
    {'name':'Nauru', 'letterCode':'NR', 'countryCode':'520'},
    {'name':'Nepal', 'letterCode':'NP', 'countryCode':'524'},
    {'name':'Netherlands', 'letterCode':'NL', 'countryCode':'528'},
    {'name':'New Caledonia', 'letterCode':'NC', 'countryCode':'540'},
    {'name':'New Zealand', 'letterCode':'NZ', 'countryCode':'554'},
    {'name':'Nicaragua', 'letterCode':'NI', 'countryCode':'558'},
    {'name':'Niger', 'letterCode':'NE', 'countryCode':'562'},
    {'name':'Nigeria', 'letterCode':'NG', 'countryCode':'566'},
    {'name':'Northern Mariana Islands', 'letterCode':'MP', 'countryCode':'580'},
    {'name':'Norway', 'letterCode':'NO', 'countryCode':'578'},
    {'name':'Oman', 'letterCode':'OM', 'countryCode':'512'},
    {'name':'Pakistan', 'letterCode':'PK', 'countryCode':'586'},
    {'name':'Palau', 'letterCode':'PW', 'countryCode':'585'},
    {'name':'Panama', 'letterCode':'PA', 'countryCode':'591'},
    {'name':'Papua New Guinea', 'letterCode':'PG', 'countryCode':'598'},
    {'name':'Paraguay', 'letterCode':'PY', 'countryCode':'600'},
    {'name':'Peru', 'letterCode':'PE', 'countryCode':'604'},
    {'name':'Philippines', 'letterCode':'PH', 'countryCode':'608'},
    {'name':'Poland', 'letterCode':'PL', 'countryCode':'616'},
    {'name':'Portugal', 'letterCode':'PT', 'countryCode':'620'},
    {'name':'Puerto Rico', 'letterCode':'PR', 'countryCode':'630'},
    {'name':'Qatar', 'letterCode':'QA', 'countryCode':'634'},
    {'name':'Romania', 'letterCode':'RO', 'countryCode':'642'},
    {'name':'Russian Federation', 'letterCode':'RU', 'countryCode':'643'},
    {'name':'Rwanda', 'letterCode':'RW', 'countryCode':'646'},
    {'name':'Saint Kitts and Nevis', 'letterCode':'KN', 'countryCode':'659'},
    {'name':'Saint Lucia', 'letterCode':'LC', 'countryCode':'662'},
    {'name':'Saint Martin (French part)', 'letterCode':'MF', 'countryCode':'663'},
    {'name':'Saint Vincent and the Grenadines', 'letterCode':'VC', 'countryCode':'670'},
    {'name':'Samoa', 'letterCode':'WS', 'countryCode':'882'},
    {'name':'San Marino', 'letterCode':'SM', 'countryCode':'674'},
    {'name':'Sao Tome and Principe', 'letterCode':'ST', 'countryCode':'678'},
    {'name':'Saudi Arabia', 'letterCode':'SA', 'countryCode':'682'},
    {'name':'Senegal', 'letterCode':'SN', 'countryCode':'686'},
    {'name':'Serbia', 'letterCode':'RS', 'countryCode':'688'},
    {'name':'Seychelles', 'letterCode':'SC', 'countryCode':'690'},
    {'name':'Sierra Leone', 'letterCode':'SL', 'countryCode':'694'},
    {'name':'Singapore', 'letterCode':'SG', 'countryCode':'702'},
    {'name':'Sint Maarten (Dutch part)', 'letterCode':'SX', 'countryCode':'534'},
    {'name':'Slovakia', 'letterCode':'SK', 'countryCode':'703'},
    {'name':'Slovenia', 'letterCode':'SI', 'countryCode':'705'},
    {'name':'Solomon Islands', 'letterCode':'SB', 'countryCode':'090'},
    {'name':'Somalia', 'letterCode':'SO', 'countryCode':'706'},
    {'name':'South Africa', 'letterCode':'ZA', 'countryCode':'710'},
    {'name':'South Sudan', 'letterCode':'SS', 'countryCode':'728'},
    {'name':'Spain', 'letterCode':'ES', 'countryCode':'724'},
    {'name':'Sri Lanka', 'letterCode':'LK', 'countryCode':'144'},
    {'name':'Sudan', 'letterCode':'SD', 'countryCode':'729'},
    {'name':'Suriname', 'letterCode':'SR', 'countryCode':'740'},
    {'name':'Sweden', 'letterCode':'SE', 'countryCode':'752'},
    {'name':'Switzerland', 'letterCode':'CH', 'countryCode':'756'},
    {'name':'Syrian Arab Republic', 'letterCode':'SY', 'countryCode':'760'},
    {'name':'Tajikistan', 'letterCode':'TJ', 'countryCode':'762'},
    {'name':'Tanzania, United Republic of', 'letterCode':'TZ', 'countryCode':'834'},
    {'name':'Thailand', 'letterCode':'TH', 'countryCode':'764'},
    {'name':'Timor-Leste', 'letterCode':'TL', 'countryCode':'626'},
    {'name':'Togo', 'letterCode':'TG', 'countryCode':'768'},
    {'name':'Tonga', 'letterCode':'TO', 'countryCode':'776'},
    {'name':'Trinidad and Tobago', 'letterCode':'TT', 'countryCode':'780'},
    {'name':'Tunisia', 'letterCode':'TN', 'countryCode':'788'},
    {'name':'Turkey', 'letterCode':'TR', 'countryCode':'792'},
    {'name':'Turkmenistan', 'letterCode':'TM', 'countryCode':'795'},
    {'name':'Turks and Caicos Islands', 'letterCode':'TC', 'countryCode':'796'},
    {'name':'Tuvalu', 'letterCode':'TV', 'countryCode':'798'},
    {'name':'Uganda', 'letterCode':'UG', 'countryCode':'800'},
    {'name':'Ukraine', 'letterCode':'UA', 'countryCode':'804'},
    {'name':'United Arab Emirates', 'letterCode':'AE', 'countryCode':'784'},
    {'name':'United Kingdom of Great Britain and Northern Ireland', 'letterCode':'GB', 'countryCode':'826'},
    {'name':'United States of America', 'letterCode':'US', 'countryCode':'840'},
    {'name':'Uruguay', 'letterCode':'UY', 'countryCode':'858'},
    {'name':'Uzbekistan', 'letterCode':'UZ', 'countryCode':'860'},
    {'name':'Vanuatu', 'letterCode':'VU', 'countryCode':'548'},
    {'name':'Venezuela (Bolivarian Republic of)', 'letterCode':'VE', 'countryCode':'862'},
    {'name':'Viet Nam', 'letterCode':'VN', 'countryCode':'704'},
    {'name':'Virgin Islands (British)', 'letterCode':'VG', 'countryCode':'092'},
    {'name':'Virgin Islands (U.S.)', 'letterCode':'VI', 'countryCode':'850'},
    {'name':'Yemen', 'letterCode':'YE', 'countryCode':'887'},
    {'name':'Zambia', 'letterCode':'ZM', 'countryCode':'894'},
    {'name':'Zimbabwe', 'letterCode':'ZW', 'countryCode':'716'}
]